### ISSUE TITLE
Unable to modify conversationData, userStorage values in Kotlin

### ISSUE THREAD

**Issue by pawelcala** [actions-on-google/actions-on-google-java#26] opened 2019-07-26 12:30 UTC
`conversationData` and `userStorage` are immutable values and cannot be changed using kotlin. 
For now there is no option to modify this! One of possible solution is to override `getResponseBuilder` in `DialogflowApp` and construct own `ResponseBuilder` with custom data BUT `ResponseBuilder` is internal class. 
Someone already noticed that in other task few months ago and you didn't fixed it yet.
Please fix this!

**Comment by Fleker** [comment] 2019-07-26 13:36
This is the same as #17, where you can clone the object to a mutable implementation.

**Comment by cbeaujoin** [comment] 2019-08-01 09:36
As said in #17 `userStorage` works fine when cloned.

But `conversationData` doesn't works.

The conversationData is overrided in ResponseSerializer.kt
https://github.com/actions-on-google/actions-on-google-java/blob/5e2c7c9b2912d2f8b11aafb05162c2c9967af5f8/src/main/kotlin/com/google/actions/api/impl/io/ResponseSerializer.kt#L94

You should put it before line 86

**Comment by Fleker** [comment] 2019-08-15 20:27
The same thing seems to work for conversation data in Kotlin

```
val sessionData = mutableMapOf<String, Any>()
        sessionData.putAll(aogRequest.conversationData)

        val headquarters = sessionData["headquarters"] as MutableList<String>
        assertEquals("google1", headquarters[0])
        headquarters[0] = "google2"

        sessionData["headquarters"] = headquarters

        val responseBuilder =
                ResponseBuilder(usesDialogflow = false, conversationData = sessionData)

        val aogResponse = responseBuilder.build()
        val jsonOutput = aogResponse.toJson()
```

**Comment by cbeaujoin** [comment] 2019-08-20 14:27
Have you noticed that conversationData is overided by the context: `[sessionId]/contexts/_actions_on_google `

**Comment by cbeaujoin** [comment] 2019-09-09 09:10
> When using Dialogflow?

Yes

**Comment by taycaldwell** [comment] 2019-09-09 17:45
Closing as a duplicate of https://github.com/actions-on-google/actions-on-google-java/issues/17

For separate/unrelated bugs, please open a new issue.

**Closed by taycaldwell** 2019-09-09 17:45 UTC
Labels: status: duplicate
