### ISSUE TITLE
Pom is malformed on maven central.

### ISSUE THREAD

**Issue by TrianReallyHard** [actions-on-google/actions-on-google-java#4] opened 2019-01-20 01:09 UTC
Just tried to compile, gave me this error.

    [WARNING] The POM for com.google.actions:actions-on-google:pom:1.0.0 is invalid, transitive dependencies (if any) will not be available: 
     2 problems were encountered while building the effective model for com.google.actions:actions-on-google:1.0.0
    [ERROR] 'dependencies.dependency.systemPath' for com.google.actions.v2:google-actions-bindings:jar must specify an absolute path but
    is ${project.basedir}/lib/libactions_java_lib.jar @
    [ERROR] 'dependencies.dependency.systemPath' for com.dialogflow.bindings:dialogflow-bindings:jar must specify an absolute path but 
    is ${project.basedir}/lib/libdialogflow_java_lib.jar @

**Comment by TrianReallyHard** [comment] 2019-01-20 01:12
Also, I found that it compiles right if you have the dependency as a system scope with the jar in the project folder, like this:

    <groupId>com.google.actions</groupId>
          <artifactId>actions-on-google</artifactId>
          <version>1.0.0</version>
          <scope>system</scope>
          <systemPath> /Users/(YourUsername)/Documents/Coding/Java/Projects/HabitGame/actions-on-google-1.0.0.jar</systemPath>

**Comment by yoichiro** [comment] 2019-01-21 14:21
I have same problem on my simple project. In my `pom.xml` file, a compiling is successful. However, for example, when launching of Jetty server with `jetty-maven-plugin` and sending a first request, a `ClassNotFoundException` is thrown.

```java
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass (WebAppClassLoader.java:556)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:521)
...
```

When I confirmed my maven local repository at this time, I could not find `org.jetbrains.kotlin:kotlin-stdlib` library and other dependent libraries in my repository. That is, my maven task could not download these dependent libraries because the `pom.xml` in the AoG Java/Kotlin Client Library is invalid, I guess.

There are some sample projects in the actions-on-google GitHub organization. However, all projects use Gradle. not Maven. Well, I guess that this library was released without any tests on Maven.

My `pom.xml` file is: https://gist.github.com/yoichiro/da973424eb957626fba7ca88611a6c40

**Comment by kishores** [comment] 2019-01-21 17:31
We are looking into this. Will post back results here.

**Comment by yoichiro** [comment] 2019-01-21 21:33
```bash
[ERROR] 'dependencies.dependency.systemPath' for com.google.actions.v2:google-actions-bindings:jar must specify an absolute path but
is ${project.basedir}/lib/libactions_java_lib.jar @
[ERROR] 'dependencies.dependency.systemPath' for com.dialogflow.bindings:dialogflow-bindings:jar must specify an absolute path but 
is ${project.basedir}/lib/libdialogflow_java_lib.jar @ 
```

Basically, I think that the cause is that the current implementation refers two jar files (libactions_java_lib.jar and libdialogflow_lib_java.jar) using the "system" scope at the following definitions:

```xml
    <dependency>
      <groupId>com.google.actions.v2</groupId>
      <artifactId>google-actions-bindings</artifactId>
      <version>1.0</version>
      <scope>system</scope>
      <systemPath>${project.basedir}/lib/libactions_java_lib.jar
      </systemPath>
    </dependency>
    <dependency>
      <groupId>com.dialogflow.bindings</groupId>
      <artifactId>dialogflow-bindings</artifactId>
      <version>1.0</version>
      <scope>system</scope>
      <systemPath>${project.basedir}/lib/libdialogflow_java_lib.jar
      </systemPath>
    </dependency>
```

Actually, all classes of these two library are included into the `actions-on-google-1.0.0.jar` file by the following definition:

```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>1.6</version>
        <executions>
          <execution>
            <id>prepare</id>
            <phase>validate</phase>
            <configuration>
              <tasks>
                <echo message="prepare phase"/>
                <unzip dest="target/classes"
                  src="${project.basedir}/lib/libactions_java_lib.jar"/>
                <unzip dest="target/classes"
                  src="${project.basedir}/lib/libdialogflow_java_lib.jar"/>
              </tasks>
            </configuration>
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

That is, actually the two "dependency" definitions above are NOT necessary. At least, they should not be included in the updated `pom.xml` file to Maven Central repository.

To solve this situation, I guess that there are the following solutions:

1. If the two libraries (libactions_lib_java.jar and libdialogflow_lib_java.jar) can be registered as each independent library to Maven central repository, the actions-on-google-java library can refer them without using the "system" scope. This is a good solution in the case that you don't want to publish these source files.
1. If you can publish these source files, they can be included in the `src` directory instead to refer the two jar files.
1. If you want to not change anything, you can specify a customized pom.xml file (that doesn't have the two dependency definitions with the "system" scope) at deploying to Maven Central repository. https://maven.apache.org/plugins/maven-deploy-plugin/examples/deploying-with-customed-pom.html

My recommendation is 1 or 2.

**Comment by kishores** [comment] 2019-01-23 00:05
Yes Yoichiro - your assessment is on point. I am looking at a solution where I mark the dependency on libactions_lib_java and libdialogflow_lib_java as "provided" as it is provided in the actions-on-google library jar file. Should have an update on this soon.

**Comment by kishores** [comment] 2019-01-23 01:34
I have fixed the pom.xml on MavenCentral. Can you please try using the 1.0.1 version as shown below?

<dependency>
	<groupId>com.google.actions</groupId>
	<artifactId>actions-on-google</artifactId>
	<version>1.0.1</version>
	<type>pom</type>
</dependency>

**Comment by yoichiro** [comment] 2019-01-23 01:51
@kishores Ok, I will test the new version. Give me a few hours.

**Comment by yoichiro** [comment] 2019-01-23 03:12
@kishores Great! The new version 1.0.1 works fine! I tested the following dependency definition:

```xml
<dependency>
	<groupId>com.google.actions</groupId>
	<artifactId>actions-on-google</artifactId>
	<version>1.0.1</version>
</dependency>
```

BTW, I think that the `<type>pom</type>` is unnecessary. Actually, if the type element specified, some errors occur (Compilation Failure).

**Comment by TrianReallyHard** [comment] 2019-01-25 18:58
Okay, so @yoichiro, should the `<type>` tags be removed?

**Comment by yoichiro** [comment] 2019-01-26 00:12
> should the <type> tags be removed?

@TrianReallyHard Yes. The `<type>pom</type>` is used for specifying a BOM project.

**Closed** 2019-01-26 00:15 UTC

**Comment by slkasisto** [comment] 2019-02-27 22:35
Where would one be looking for these dependencies:

```
<dependency>
      <groupId>com.google.actions</groupId>
      <artifactId>actions-bindings</artifactId>
      <version>2.0.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.actions</groupId>
      <artifactId>dialogflow-bindings</artifactId>
      <version>2.0.0</version>
      <scope>provided</scope>
    </dependency>
```

They don't seem to be available on search.maven.org and instead went to sonatype repo as pointed here: https://stackoverflow.com/questions/54585915/which-jar-houses-com-google-api-services-actions-fulfillment-v2-model-packag.  Why the inconsistency?

**Comment by Fleker** [comment] 2019-02-28 14:23
Those two files should originate as jar files that are embedded in the library source, and aren't hosted directly on Maven.
